/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAppelfoncExp7 extends PExp7
{
    private TId _id_;
    private TPo _po_;
    private PListeexp _listeexp_;
    private TPf _pf_;

    public AAppelfoncExp7()
    {
        // Constructor
    }

    public AAppelfoncExp7(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TPo _po_,
        @SuppressWarnings("hiding") PListeexp _listeexp_,
        @SuppressWarnings("hiding") TPf _pf_)
    {
        // Constructor
        setId(_id_);

        setPo(_po_);

        setListeexp(_listeexp_);

        setPf(_pf_);

    }

    @Override
    public Object clone()
    {
        return new AAppelfoncExp7(
            cloneNode(this._id_),
            cloneNode(this._po_),
            cloneNode(this._listeexp_),
            cloneNode(this._pf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppelfoncExp7(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TPo getPo()
    {
        return this._po_;
    }

    public void setPo(TPo node)
    {
        if(this._po_ != null)
        {
            this._po_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._po_ = node;
    }

    public PListeexp getListeexp()
    {
        return this._listeexp_;
    }

    public void setListeexp(PListeexp node)
    {
        if(this._listeexp_ != null)
        {
            this._listeexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeexp_ = node;
    }

    public TPf getPf()
    {
        return this._pf_;
    }

    public void setPf(TPf node)
    {
        if(this._pf_ != null)
        {
            this._pf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._po_)
            + toString(this._listeexp_)
            + toString(this._pf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._po_ == child)
        {
            this._po_ = null;
            return;
        }

        if(this._listeexp_ == child)
        {
            this._listeexp_ = null;
            return;
        }

        if(this._pf_ == child)
        {
            this._pf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._po_ == oldChild)
        {
            setPo((TPo) newChild);
            return;
        }

        if(this._listeexp_ == oldChild)
        {
            setListeexp((PListeexp) newChild);
            return;
        }

        if(this._pf_ == oldChild)
        {
            setPf((TPf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
