/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ACas48Var extends PVar
{
    private TId _id_;
    private TAco _aco_;
    private PExp _exp_;
    private TAcf _acf_;

    public ACas48Var()
    {
        // Constructor
    }

    public ACas48Var(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TAco _aco_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TAcf _acf_)
    {
        // Constructor
        setId(_id_);

        setAco(_aco_);

        setExp(_exp_);

        setAcf(_acf_);

    }

    @Override
    public Object clone()
    {
        return new ACas48Var(
            cloneNode(this._id_),
            cloneNode(this._aco_),
            cloneNode(this._exp_),
            cloneNode(this._acf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACas48Var(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TAco getAco()
    {
        return this._aco_;
    }

    public void setAco(TAco node)
    {
        if(this._aco_ != null)
        {
            this._aco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aco_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TAcf getAcf()
    {
        return this._acf_;
    }

    public void setAcf(TAcf node)
    {
        if(this._acf_ != null)
        {
            this._acf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._acf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aco_)
            + toString(this._exp_)
            + toString(this._acf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aco_ == child)
        {
            this._aco_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._acf_ == child)
        {
            this._acf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._aco_ == oldChild)
        {
            setAco((TAco) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._acf_ == oldChild)
        {
            setAcf((TAcf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
