/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstInst extends PInst
{
    private PVar _var_;
    private TEgale _egale_;
    private PExp _exp_;
    private TPvirgule _pvirgule_;

    public AInstInst()
    {
        // Constructor
    }

    public AInstInst(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TEgale _egale_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TPvirgule _pvirgule_)
    {
        // Constructor
        setVar(_var_);

        setEgale(_egale_);

        setExp(_exp_);

        setPvirgule(_pvirgule_);

    }

    @Override
    public Object clone()
    {
        return new AInstInst(
            cloneNode(this._var_),
            cloneNode(this._egale_),
            cloneNode(this._exp_),
            cloneNode(this._pvirgule_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstInst(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TEgale getEgale()
    {
        return this._egale_;
    }

    public void setEgale(TEgale node)
    {
        if(this._egale_ != null)
        {
            this._egale_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._egale_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TPvirgule getPvirgule()
    {
        return this._pvirgule_;
    }

    public void setPvirgule(TPvirgule node)
    {
        if(this._pvirgule_ != null)
        {
            this._pvirgule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvirgule_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._egale_)
            + toString(this._exp_)
            + toString(this._pvirgule_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._egale_ == child)
        {
            this._egale_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._pvirgule_ == child)
        {
            this._pvirgule_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._egale_ == oldChild)
        {
            setEgale((TEgale) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._pvirgule_ == oldChild)
        {
            setPvirgule((TPvirgule) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
