/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ARetournInst extends PInst
{
    private TRetourne _retourne_;
    private PExp _exp_;
    private TPvirgule _pvirgule_;

    public ARetournInst()
    {
        // Constructor
    }

    public ARetournInst(
        @SuppressWarnings("hiding") TRetourne _retourne_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TPvirgule _pvirgule_)
    {
        // Constructor
        setRetourne(_retourne_);

        setExp(_exp_);

        setPvirgule(_pvirgule_);

    }

    @Override
    public Object clone()
    {
        return new ARetournInst(
            cloneNode(this._retourne_),
            cloneNode(this._exp_),
            cloneNode(this._pvirgule_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARetournInst(this);
    }

    public TRetourne getRetourne()
    {
        return this._retourne_;
    }

    public void setRetourne(TRetourne node)
    {
        if(this._retourne_ != null)
        {
            this._retourne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._retourne_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TPvirgule getPvirgule()
    {
        return this._pvirgule_;
    }

    public void setPvirgule(TPvirgule node)
    {
        if(this._pvirgule_ != null)
        {
            this._pvirgule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvirgule_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._retourne_)
            + toString(this._exp_)
            + toString(this._pvirgule_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._retourne_ == child)
        {
            this._retourne_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._pvirgule_ == child)
        {
            this._pvirgule_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._retourne_ == oldChild)
        {
            setRetourne((TRetourne) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._pvirgule_ == oldChild)
        {
            setPvirgule((TPvirgule) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
