/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AVarDecvar extends PDecvar
{
    private PTypevar _typevar_;
    private TId _id_;

    public AVarDecvar()
    {
        // Constructor
    }

    public AVarDecvar(
        @SuppressWarnings("hiding") PTypevar _typevar_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setTypevar(_typevar_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AVarDecvar(
            cloneNode(this._typevar_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDecvar(this);
    }

    public PTypevar getTypevar()
    {
        return this._typevar_;
    }

    public void setTypevar(PTypevar node)
    {
        if(this._typevar_ != null)
        {
            this._typevar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typevar_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typevar_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typevar_ == child)
        {
            this._typevar_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typevar_ == oldChild)
        {
            setTypevar((PTypevar) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
