/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TVrai extends Token
{
    public TVrai()
    {
        super.setText("vrai");
    }

    public TVrai(int line, int pos)
    {
        super.setText("vrai");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVrai(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVrai(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVrai text.");
    }
}
