/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.parser;

import sc.lexer.*;
import sc.node.*;
import sc.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList<Object> listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgramme node1 = (PProgramme) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce ADecvar1Programme */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list);
            }
            break;
            case 1: /* reduce AVide1Programme */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list);
            }
            break;
            case 2: /* reduce AListdecvarListedecvarbis */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list);
            }
            break;
            case 3: /* reduce AVideListedecvarbis */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list);
            }
            break;
            case 4: /* reduce AVarDecvar */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list);
            }
            break;
            case 5: /* reduce AFoncDecvar */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list);
            }
            break;
            case 6: /* reduce ABooleanTypevar */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list);
            }
            break;
            case 7: /* reduce AEntierTypevar */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list);
            }
            break;
            case 8: /* reduce ADecfoncListedecfonc */
            {
                ArrayList<Object> list = new8();
                push(goTo(4), list);
            }
            break;
            case 9: /* reduce AVideListedecfonc */
            {
                ArrayList<Object> list = new9();
                push(goTo(4), list);
            }
            break;
            case 10: /* reduce ADecvar1$Decvar2$Typeop1Decfonc */
            {
                ArrayList<Object> list = new10();
                push(goTo(5), list);
            }
            break;
            case 11: /* reduce ADecvar1$Decvar2$Vide1Decfonc */
            {
                ArrayList<Object> list = new11();
                push(goTo(5), list);
            }
            break;
            case 12: /* reduce ADecvar1$Vide2$Typeop1Decfonc */
            {
                ArrayList<Object> list = new12();
                push(goTo(5), list);
            }
            break;
            case 13: /* reduce ADecvar1$Vide2$Vide1Decfonc */
            {
                ArrayList<Object> list = new13();
                push(goTo(5), list);
            }
            break;
            case 14: /* reduce AVide1$Decvar2$Typeop1Decfonc */
            {
                ArrayList<Object> list = new14();
                push(goTo(5), list);
            }
            break;
            case 15: /* reduce AVide1$Decvar2$Vide1Decfonc */
            {
                ArrayList<Object> list = new15();
                push(goTo(5), list);
            }
            break;
            case 16: /* reduce AVide1$Vide2$Typeop1Decfonc */
            {
                ArrayList<Object> list = new16();
                push(goTo(5), list);
            }
            break;
            case 17: /* reduce AVide1$Vide2$Vide1Decfonc */
            {
                ArrayList<Object> list = new17();
                push(goTo(5), list);
            }
            break;
            case 18: /* reduce ABlocinst */
            {
                ArrayList<Object> list = new18();
                push(goTo(6), list);
            }
            break;
            case 19: /* reduce AListinstListeinst */
            {
                ArrayList<Object> list = new19();
                push(goTo(7), list);
            }
            break;
            case 20: /* reduce AVideListeinst */
            {
                ArrayList<Object> list = new20();
                push(goTo(7), list);
            }
            break;
            case 21: /* reduce AInstInst */
            {
                ArrayList<Object> list = new21();
                push(goTo(8), list);
            }
            break;
            case 22: /* reduce ATanqueInst */
            {
                ArrayList<Object> list = new22();
                push(goTo(8), list);
            }
            break;
            case 23: /* reduce ASiInst */
            {
                ArrayList<Object> list = new23();
                push(goTo(8), list);
            }
            break;
            case 24: /* reduce ASisinonInst */
            {
                ArrayList<Object> list = new24();
                push(goTo(8), list);
            }
            break;
            case 25: /* reduce ARetournInst */
            {
                ArrayList<Object> list = new25();
                push(goTo(8), list);
            }
            break;
            case 26: /* reduce AAppfoncInst */
            {
                ArrayList<Object> list = new26();
                push(goTo(8), list);
            }
            break;
            case 27: /* reduce AEcrireInst */
            {
                ArrayList<Object> list = new27();
                push(goTo(8), list);
            }
            break;
            case 28: /* reduce AListexpListeexp */
            {
                ArrayList<Object> list = new28();
                push(goTo(9), list);
            }
            break;
            case 29: /* reduce AVideListeexp */
            {
                ArrayList<Object> list = new29();
                push(goTo(9), list);
            }
            break;
            case 30: /* reduce AListexpbisListeexpbis */
            {
                ArrayList<Object> list = new30();
                push(goTo(10), list);
            }
            break;
            case 31: /* reduce AVideListeexpbis */
            {
                ArrayList<Object> list = new31();
                push(goTo(10), list);
            }
            break;
            case 32: /* reduce AOuExp */
            {
                ArrayList<Object> list = new32();
                push(goTo(11), list);
            }
            break;
            case 33: /* reduce AExp2Exp */
            {
                ArrayList<Object> list = new33();
                push(goTo(11), list);
            }
            break;
            case 34: /* reduce AEtExp2 */
            {
                ArrayList<Object> list = new34();
                push(goTo(12), list);
            }
            break;
            case 35: /* reduce AExp3Exp2 */
            {
                ArrayList<Object> list = new35();
                push(goTo(12), list);
            }
            break;
            case 36: /* reduce AEgaleExp3 */
            {
                ArrayList<Object> list = new36();
                push(goTo(13), list);
            }
            break;
            case 37: /* reduce AInfExp3 */
            {
                ArrayList<Object> list = new37();
                push(goTo(13), list);
            }
            break;
            case 38: /* reduce AExp4Exp3 */
            {
                ArrayList<Object> list = new38();
                push(goTo(13), list);
            }
            break;
            case 39: /* reduce APlusExp4 */
            {
                ArrayList<Object> list = new39();
                push(goTo(14), list);
            }
            break;
            case 40: /* reduce AMoinsExp4 */
            {
                ArrayList<Object> list = new40();
                push(goTo(14), list);
            }
            break;
            case 41: /* reduce AExp5Exp4 */
            {
                ArrayList<Object> list = new41();
                push(goTo(14), list);
            }
            break;
            case 42: /* reduce ADivExp5 */
            {
                ArrayList<Object> list = new42();
                push(goTo(15), list);
            }
            break;
            case 43: /* reduce AMultExp5 */
            {
                ArrayList<Object> list = new43();
                push(goTo(15), list);
            }
            break;
            case 44: /* reduce AExp6Exp5 */
            {
                ArrayList<Object> list = new44();
                push(goTo(15), list);
            }
            break;
            case 45: /* reduce ANonExp6 */
            {
                ArrayList<Object> list = new45();
                push(goTo(16), list);
            }
            break;
            case 46: /* reduce AExp7Exp6 */
            {
                ArrayList<Object> list = new46();
                push(goTo(16), list);
            }
            break;
            case 47: /* reduce AExpbExp7 */
            {
                ArrayList<Object> list = new47();
                push(goTo(17), list);
            }
            break;
            case 48: /* reduce AVarExp7 */
            {
                ArrayList<Object> list = new48();
                push(goTo(17), list);
            }
            break;
            case 49: /* reduce ANombreExp7 */
            {
                ArrayList<Object> list = new49();
                push(goTo(17), list);
            }
            break;
            case 50: /* reduce AAppelfoncExp7 */
            {
                ArrayList<Object> list = new50();
                push(goTo(17), list);
            }
            break;
            case 51: /* reduce ALireExp7 */
            {
                ArrayList<Object> list = new51();
                push(goTo(17), list);
            }
            break;
            case 52: /* reduce AVraiExp7 */
            {
                ArrayList<Object> list = new52();
                push(goTo(17), list);
            }
            break;
            case 53: /* reduce AFauxExp7 */
            {
                ArrayList<Object> list = new53();
                push(goTo(17), list);
            }
            break;
            case 54: /* reduce AIdVar */
            {
                ArrayList<Object> list = new54();
                push(goTo(18), list);
            }
            break;
            case 55: /* reduce AIdbVar */
            {
                ArrayList<Object> list = new55();
                push(goTo(18), list);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce ADecvar1Programme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PListedecvar plistedecvarNode2;
        PListedecfonc plistedecfoncNode5;
        {
            // Block
        PDecvar pdecvarNode3;
        PListedecvarbis plistedecvarbisNode4;
        pdecvarNode3 = (PDecvar)nodeArrayList1.get(0);
        plistedecvarbisNode4 = (PListedecvarbis)nodeArrayList2.get(0);

        plistedecvarNode2 = new ADecvarListedecvar(pdecvarNode3, plistedecvarbisNode4);
        }
        plistedecfoncNode5 = (PListedecfonc)nodeArrayList3.get(0);

        pprogrammeNode1 = new AProgramme(plistedecvarNode2, plistedecfoncNode5);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AVide1Programme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PListedecvar plistedecvarNode2;
        PListedecfonc plistedecfoncNode3;
        {
            // Block

        plistedecvarNode2 = new AVideListedecvar();
        }
        plistedecfoncNode3 = (PListedecfonc)nodeArrayList1.get(0);

        pprogrammeNode1 = new AProgramme(plistedecvarNode2, plistedecfoncNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AListdecvarListedecvarbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListedecvarbis plistedecvarbisNode1;
        {
            // Block
        TVirgule tvirguleNode2;
        PDecvar pdecvarNode3;
        PListedecvarbis plistedecvarbisNode4;
        tvirguleNode2 = (TVirgule)nodeArrayList1.get(0);
        pdecvarNode3 = (PDecvar)nodeArrayList2.get(0);
        plistedecvarbisNode4 = (PListedecvarbis)nodeArrayList3.get(0);

        plistedecvarbisNode1 = new AListdecvarListedecvarbis(tvirguleNode2, pdecvarNode3, plistedecvarbisNode4);
        }
	nodeList.add(plistedecvarbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AVideListedecvarbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListedecvarbis plistedecvarbisNode1;
        {
            // Block

        plistedecvarbisNode1 = new AVideListedecvarbis();
        }
	nodeList.add(plistedecvarbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AVarDecvar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecvar pdecvarNode1;
        {
            // Block
        PTypevar ptypevarNode2;
        TId tidNode3;
        ptypevarNode2 = (PTypevar)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pdecvarNode1 = new AVarDecvar(ptypevarNode2, tidNode3);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AFoncDecvar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecvar pdecvarNode1;
        {
            // Block
        PTypevar ptypevarNode2;
        TId tidNode3;
        TCo tcoNode4;
        TNombre tnombreNode5;
        TCf tcfNode6;
        ptypevarNode2 = (PTypevar)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tcoNode4 = (TCo)nodeArrayList3.get(0);
        tnombreNode5 = (TNombre)nodeArrayList4.get(0);
        tcfNode6 = (TCf)nodeArrayList5.get(0);

        pdecvarNode1 = new AFoncDecvar(ptypevarNode2, tidNode3, tcoNode4, tnombreNode5, tcfNode6);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce ABooleanTypevar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTypevar ptypevarNode1;
        {
            // Block
        TBoolean tbooleanNode2;
        tbooleanNode2 = (TBoolean)nodeArrayList1.get(0);

        ptypevarNode1 = new ABooleanTypevar(tbooleanNode2);
        }
	nodeList.add(ptypevarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AEntierTypevar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTypevar ptypevarNode1;
        {
            // Block
        TEntier tentierNode2;
        tentierNode2 = (TEntier)nodeArrayList1.get(0);

        ptypevarNode1 = new AEntierTypevar(tentierNode2);
        }
	nodeList.add(ptypevarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ADecfoncListedecfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListedecfonc plistedecfoncNode1;
        {
            // Block
        PDecfonc pdecfoncNode2;
        PListedecfonc plistedecfoncNode3;
        pdecfoncNode2 = (PDecfonc)nodeArrayList1.get(0);
        plistedecfoncNode3 = (PListedecfonc)nodeArrayList2.get(0);

        plistedecfoncNode1 = new ADecfoncListedecfonc(pdecfoncNode2, plistedecfoncNode3);
        }
	nodeList.add(plistedecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AVideListedecfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListedecfonc plistedecfoncNode1;
        {
            // Block

        plistedecfoncNode1 = new AVideListedecfonc();
        }
	nodeList.add(plistedecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ADecvar1$Decvar2$Typeop1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode4;
        TPo tpoNode5;
        PListedecvar plistedecvarNode6;
        TPf tpfNode9;
        PListedecvar plistedecvarNode10;
        PBlocinst pblocinstNode13;
        {
            // Block
        PTypevar ptypevarNode3;
        ptypevarNode3 = (PTypevar)nodeArrayList1.get(0);

        ptypeopNode2 = new ATypeopTypeop(ptypevarNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block
        PDecvar pdecvarNode7;
        PListedecvarbis plistedecvarbisNode8;
        pdecvarNode7 = (PDecvar)nodeArrayList4.get(0);
        plistedecvarbisNode8 = (PListedecvarbis)nodeArrayList5.get(0);

        plistedecvarNode6 = new ADecvarListedecvar(pdecvarNode7, plistedecvarbisNode8);
        }
        tpfNode9 = (TPf)nodeArrayList6.get(0);
        {
            // Block
        PDecvar pdecvarNode11;
        PListedecvarbis plistedecvarbisNode12;
        pdecvarNode11 = (PDecvar)nodeArrayList7.get(0);
        plistedecvarbisNode12 = (PListedecvarbis)nodeArrayList8.get(0);

        plistedecvarNode10 = new ADecvarListedecvar(pdecvarNode11, plistedecvarbisNode12);
        }
        pblocinstNode13 = (PBlocinst)nodeArrayList9.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode4, tpoNode5, plistedecvarNode6, tpfNode9, plistedecvarNode10, pblocinstNode13);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ADecvar1$Decvar2$Vide1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode3;
        TPo tpoNode4;
        PListedecvar plistedecvarNode5;
        TPf tpfNode8;
        PListedecvar plistedecvarNode9;
        PBlocinst pblocinstNode12;
        {
            // Block

        ptypeopNode2 = new AVideTypeop();
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tpoNode4 = (TPo)nodeArrayList2.get(0);
        {
            // Block
        PDecvar pdecvarNode6;
        PListedecvarbis plistedecvarbisNode7;
        pdecvarNode6 = (PDecvar)nodeArrayList3.get(0);
        plistedecvarbisNode7 = (PListedecvarbis)nodeArrayList4.get(0);

        plistedecvarNode5 = new ADecvarListedecvar(pdecvarNode6, plistedecvarbisNode7);
        }
        tpfNode8 = (TPf)nodeArrayList5.get(0);
        {
            // Block
        PDecvar pdecvarNode10;
        PListedecvarbis plistedecvarbisNode11;
        pdecvarNode10 = (PDecvar)nodeArrayList6.get(0);
        plistedecvarbisNode11 = (PListedecvarbis)nodeArrayList7.get(0);

        plistedecvarNode9 = new ADecvarListedecvar(pdecvarNode10, plistedecvarbisNode11);
        }
        pblocinstNode12 = (PBlocinst)nodeArrayList8.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode3, tpoNode4, plistedecvarNode5, tpfNode8, plistedecvarNode9, pblocinstNode12);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce ADecvar1$Vide2$Typeop1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode4;
        TPo tpoNode5;
        PListedecvar plistedecvarNode6;
        TPf tpfNode9;
        PListedecvar plistedecvarNode10;
        PBlocinst pblocinstNode11;
        {
            // Block
        PTypevar ptypevarNode3;
        ptypevarNode3 = (PTypevar)nodeArrayList1.get(0);

        ptypeopNode2 = new ATypeopTypeop(ptypevarNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block
        PDecvar pdecvarNode7;
        PListedecvarbis plistedecvarbisNode8;
        pdecvarNode7 = (PDecvar)nodeArrayList4.get(0);
        plistedecvarbisNode8 = (PListedecvarbis)nodeArrayList5.get(0);

        plistedecvarNode6 = new ADecvarListedecvar(pdecvarNode7, plistedecvarbisNode8);
        }
        tpfNode9 = (TPf)nodeArrayList6.get(0);
        {
            // Block

        plistedecvarNode10 = new AVideListedecvar();
        }
        pblocinstNode11 = (PBlocinst)nodeArrayList7.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode4, tpoNode5, plistedecvarNode6, tpfNode9, plistedecvarNode10, pblocinstNode11);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ADecvar1$Vide2$Vide1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode3;
        TPo tpoNode4;
        PListedecvar plistedecvarNode5;
        TPf tpfNode8;
        PListedecvar plistedecvarNode9;
        PBlocinst pblocinstNode10;
        {
            // Block

        ptypeopNode2 = new AVideTypeop();
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tpoNode4 = (TPo)nodeArrayList2.get(0);
        {
            // Block
        PDecvar pdecvarNode6;
        PListedecvarbis plistedecvarbisNode7;
        pdecvarNode6 = (PDecvar)nodeArrayList3.get(0);
        plistedecvarbisNode7 = (PListedecvarbis)nodeArrayList4.get(0);

        plistedecvarNode5 = new ADecvarListedecvar(pdecvarNode6, plistedecvarbisNode7);
        }
        tpfNode8 = (TPf)nodeArrayList5.get(0);
        {
            // Block

        plistedecvarNode9 = new AVideListedecvar();
        }
        pblocinstNode10 = (PBlocinst)nodeArrayList6.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode3, tpoNode4, plistedecvarNode5, tpfNode8, plistedecvarNode9, pblocinstNode10);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AVide1$Decvar2$Typeop1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode4;
        TPo tpoNode5;
        PListedecvar plistedecvarNode6;
        TPf tpfNode7;
        PListedecvar plistedecvarNode8;
        PBlocinst pblocinstNode11;
        {
            // Block
        PTypevar ptypevarNode3;
        ptypevarNode3 = (PTypevar)nodeArrayList1.get(0);

        ptypeopNode2 = new ATypeopTypeop(ptypevarNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block

        plistedecvarNode6 = new AVideListedecvar();
        }
        tpfNode7 = (TPf)nodeArrayList4.get(0);
        {
            // Block
        PDecvar pdecvarNode9;
        PListedecvarbis plistedecvarbisNode10;
        pdecvarNode9 = (PDecvar)nodeArrayList5.get(0);
        plistedecvarbisNode10 = (PListedecvarbis)nodeArrayList6.get(0);

        plistedecvarNode8 = new ADecvarListedecvar(pdecvarNode9, plistedecvarbisNode10);
        }
        pblocinstNode11 = (PBlocinst)nodeArrayList7.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode4, tpoNode5, plistedecvarNode6, tpfNode7, plistedecvarNode8, pblocinstNode11);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce AVide1$Decvar2$Vide1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode3;
        TPo tpoNode4;
        PListedecvar plistedecvarNode5;
        TPf tpfNode6;
        PListedecvar plistedecvarNode7;
        PBlocinst pblocinstNode10;
        {
            // Block

        ptypeopNode2 = new AVideTypeop();
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tpoNode4 = (TPo)nodeArrayList2.get(0);
        {
            // Block

        plistedecvarNode5 = new AVideListedecvar();
        }
        tpfNode6 = (TPf)nodeArrayList3.get(0);
        {
            // Block
        PDecvar pdecvarNode8;
        PListedecvarbis plistedecvarbisNode9;
        pdecvarNode8 = (PDecvar)nodeArrayList4.get(0);
        plistedecvarbisNode9 = (PListedecvarbis)nodeArrayList5.get(0);

        plistedecvarNode7 = new ADecvarListedecvar(pdecvarNode8, plistedecvarbisNode9);
        }
        pblocinstNode10 = (PBlocinst)nodeArrayList6.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode3, tpoNode4, plistedecvarNode5, tpfNode6, plistedecvarNode7, pblocinstNode10);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AVide1$Vide2$Typeop1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode4;
        TPo tpoNode5;
        PListedecvar plistedecvarNode6;
        TPf tpfNode7;
        PListedecvar plistedecvarNode8;
        PBlocinst pblocinstNode9;
        {
            // Block
        PTypevar ptypevarNode3;
        ptypevarNode3 = (PTypevar)nodeArrayList1.get(0);

        ptypeopNode2 = new ATypeopTypeop(ptypevarNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block

        plistedecvarNode6 = new AVideListedecvar();
        }
        tpfNode7 = (TPf)nodeArrayList4.get(0);
        {
            // Block

        plistedecvarNode8 = new AVideListedecvar();
        }
        pblocinstNode9 = (PBlocinst)nodeArrayList5.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode4, tpoNode5, plistedecvarNode6, tpfNode7, plistedecvarNode8, pblocinstNode9);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AVide1$Vide2$Vide1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        PTypeop ptypeopNode2;
        TId tidNode3;
        TPo tpoNode4;
        PListedecvar plistedecvarNode5;
        TPf tpfNode6;
        PListedecvar plistedecvarNode7;
        PBlocinst pblocinstNode8;
        {
            // Block

        ptypeopNode2 = new AVideTypeop();
        }
        tidNode3 = (TId)nodeArrayList1.get(0);
        tpoNode4 = (TPo)nodeArrayList2.get(0);
        {
            // Block

        plistedecvarNode5 = new AVideListedecvar();
        }
        tpfNode6 = (TPf)nodeArrayList3.get(0);
        {
            // Block

        plistedecvarNode7 = new AVideListedecvar();
        }
        pblocinstNode8 = (PBlocinst)nodeArrayList4.get(0);

        pdecfoncNode1 = new ADecfonc(ptypeopNode2, tidNode3, tpoNode4, plistedecvarNode5, tpfNode6, plistedecvarNode7, pblocinstNode8);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce ABlocinst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PBlocinst pblocinstNode1;
        {
            // Block
        TAco tacoNode2;
        PListeinst plisteinstNode3;
        TAcf tacfNode4;
        tacoNode2 = (TAco)nodeArrayList1.get(0);
        plisteinstNode3 = (PListeinst)nodeArrayList2.get(0);
        tacfNode4 = (TAcf)nodeArrayList3.get(0);

        pblocinstNode1 = new ABlocinst(tacoNode2, plisteinstNode3, tacfNode4);
        }
	nodeList.add(pblocinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AListinstListeinst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListeinst plisteinstNode1;
        {
            // Block
        PInst pinstNode2;
        PListeinst plisteinstNode3;
        pinstNode2 = (PInst)nodeArrayList1.get(0);
        plisteinstNode3 = (PListeinst)nodeArrayList2.get(0);

        plisteinstNode1 = new AListinstListeinst(pinstNode2, plisteinstNode3);
        }
	nodeList.add(plisteinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AVideListeinst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListeinst plisteinstNode1;
        {
            // Block

        plisteinstNode1 = new AVideListeinst();
        }
	nodeList.add(plisteinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AInstInst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInst pinstNode1;
        {
            // Block
        PVar pvarNode2;
        TEgale tegaleNode3;
        PExp pexpNode4;
        TPvirgule tpvirguleNode5;
        pvarNode2 = (PVar)nodeArrayList1.get(0);
        tegaleNode3 = (TEgale)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tpvirguleNode5 = (TPvirgule)nodeArrayList4.get(0);

        pinstNode1 = new AInstInst(pvarNode2, tegaleNode3, pexpNode4, tpvirguleNode5);
        }
	nodeList.add(pinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce ATanqueInst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInst pinstNode1;
        {
            // Block
        TTantque ttantqueNode2;
        PExp pexpNode3;
        TFaire tfaireNode4;
        PBlocinst pblocinstNode5;
        ttantqueNode2 = (TTantque)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tfaireNode4 = (TFaire)nodeArrayList3.get(0);
        pblocinstNode5 = (PBlocinst)nodeArrayList4.get(0);

        pinstNode1 = new ATanqueInst(ttantqueNode2, pexpNode3, tfaireNode4, pblocinstNode5);
        }
	nodeList.add(pinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce ASiInst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInst pinstNode1;
        {
            // Block
        TSi tsiNode2;
        PExp pexpNode3;
        TAlors talorsNode4;
        PBlocinst pblocinstNode5;
        tsiNode2 = (TSi)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        talorsNode4 = (TAlors)nodeArrayList3.get(0);
        pblocinstNode5 = (PBlocinst)nodeArrayList4.get(0);

        pinstNode1 = new ASiInst(tsiNode2, pexpNode3, talorsNode4, pblocinstNode5);
        }
	nodeList.add(pinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce ASisinonInst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInst pinstNode1;
        {
            // Block
        TSi tsiNode2;
        PExp pexpNode3;
        TAlors talorsNode4;
        PBlocinst pblocinstNode5;
        TSinon tsinonNode6;
        PBlocinst pblocinstNode7;
        tsiNode2 = (TSi)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        talorsNode4 = (TAlors)nodeArrayList3.get(0);
        pblocinstNode5 = (PBlocinst)nodeArrayList4.get(0);
        tsinonNode6 = (TSinon)nodeArrayList5.get(0);
        pblocinstNode7 = (PBlocinst)nodeArrayList6.get(0);

        pinstNode1 = new ASisinonInst(tsiNode2, pexpNode3, talorsNode4, pblocinstNode5, tsinonNode6, pblocinstNode7);
        }
	nodeList.add(pinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce ARetournInst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInst pinstNode1;
        {
            // Block
        TRetourne tretourneNode2;
        PExp pexpNode3;
        TPvirgule tpvirguleNode4;
        tretourneNode2 = (TRetourne)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tpvirguleNode4 = (TPvirgule)nodeArrayList3.get(0);

        pinstNode1 = new ARetournInst(tretourneNode2, pexpNode3, tpvirguleNode4);
        }
	nodeList.add(pinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce AAppfoncInst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInst pinstNode1;
        {
            // Block
        TId tidNode2;
        TPo tpoNode3;
        PListeexp plisteexpNode4;
        TPf tpfNode5;
        TPvirgule tpvirguleNode6;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        plisteexpNode4 = (PListeexp)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);
        tpvirguleNode6 = (TPvirgule)nodeArrayList5.get(0);

        pinstNode1 = new AAppfoncInst(tidNode2, tpoNode3, plisteexpNode4, tpfNode5, tpvirguleNode6);
        }
	nodeList.add(pinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AEcrireInst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInst pinstNode1;
        {
            // Block
        TEcrire tecrireNode2;
        TPo tpoNode3;
        PExp pexpNode4;
        TPf tpfNode5;
        TPvirgule tpvirguleNode6;
        tecrireNode2 = (TEcrire)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);
        tpvirguleNode6 = (TPvirgule)nodeArrayList5.get(0);

        pinstNode1 = new AEcrireInst(tecrireNode2, tpoNode3, pexpNode4, tpfNode5, tpvirguleNode6);
        }
	nodeList.add(pinstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AListexpListeexp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListeexp plisteexpNode1;
        {
            // Block
        PExp pexpNode2;
        PListeexpbis plisteexpbisNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        plisteexpbisNode3 = (PListeexpbis)nodeArrayList2.get(0);

        plisteexpNode1 = new AListexpListeexp(pexpNode2, plisteexpbisNode3);
        }
	nodeList.add(plisteexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AVideListeexp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListeexp plisteexpNode1;
        {
            // Block

        plisteexpNode1 = new AVideListeexp();
        }
	nodeList.add(plisteexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AListexpbisListeexpbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListeexpbis plisteexpbisNode1;
        {
            // Block
        TVirgule tvirguleNode2;
        PExp pexpNode3;
        PListeexpbis plisteexpbisNode4;
        tvirguleNode2 = (TVirgule)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        plisteexpbisNode4 = (PListeexpbis)nodeArrayList3.get(0);

        plisteexpbisNode1 = new AListexpbisListeexpbis(tvirguleNode2, pexpNode3, plisteexpbisNode4);
        }
	nodeList.add(plisteexpbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AVideListeexpbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListeexpbis plisteexpbisNode1;
        {
            // Block

        plisteexpbisNode1 = new AVideListeexpbis();
        }
	nodeList.add(plisteexpbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AOuExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TOu touNode3;
        PExp2 pexp2Node4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        touNode3 = (TOu)nodeArrayList2.get(0);
        pexp2Node4 = (PExp2)nodeArrayList3.get(0);

        pexpNode1 = new AOuExp(pexpNode2, touNode3, pexp2Node4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AExp2Exp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp2 pexp2Node2;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);

        pexpNode1 = new AExp2Exp(pexp2Node2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AEtExp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp2 pexp2Node2;
        TEt tetNode3;
        PExp3 pexp3Node4;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);
        tetNode3 = (TEt)nodeArrayList2.get(0);
        pexp3Node4 = (PExp3)nodeArrayList3.get(0);

        pexp2Node1 = new AEtExp2(pexp2Node2, tetNode3, pexp3Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AExp3Exp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp3 pexp3Node2;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);

        pexp2Node1 = new AExp3Exp2(pexp3Node2);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AEgaleExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TEgale tegaleNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tegaleNode3 = (TEgale)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new AEgaleExp3(pexp3Node2, tegaleNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce AInfExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TInf tinfNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tinfNode3 = (TInf)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new AInfExp3(pexp3Node2, tinfNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AExp4Exp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp4 pexp4Node2;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);

        pexp3Node1 = new AExp4Exp3(pexp4Node2);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce APlusExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TPlus tplusNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new APlusExp4(pexp4Node2, tplusNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AMoinsExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TMoins tmoinsNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tmoinsNode3 = (TMoins)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new AMoinsExp4(pexp4Node2, tmoinsNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AExp5Exp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp5 pexp5Node2;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);

        pexp4Node1 = new AExp5Exp4(pexp5Node2);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce ADivExp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp5 pexp5Node2;
        TDiv tdivNode3;
        PExp6 pexp6Node4;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        pexp6Node4 = (PExp6)nodeArrayList3.get(0);

        pexp5Node1 = new ADivExp5(pexp5Node2, tdivNode3, pexp6Node4);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce AMultExp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp5 pexp5Node2;
        TMult tmultNode3;
        PExp6 pexp6Node4;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        pexp6Node4 = (PExp6)nodeArrayList3.get(0);

        pexp5Node1 = new AMultExp5(pexp5Node2, tmultNode3, pexp6Node4);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce AExp6Exp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp6 pexp6Node2;
        pexp6Node2 = (PExp6)nodeArrayList1.get(0);

        pexp5Node1 = new AExp6Exp5(pexp6Node2);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce ANonExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TNon tnonNode2;
        PExp6 pexp6Node3;
        tnonNode2 = (TNon)nodeArrayList1.get(0);
        pexp6Node3 = (PExp6)nodeArrayList2.get(0);

        pexp6Node1 = new ANonExp6(tnonNode2, pexp6Node3);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AExp7Exp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        PExp7 pexp7Node2;
        pexp7Node2 = (PExp7)nodeArrayList1.get(0);

        pexp6Node1 = new AExp7Exp6(pexp7Node2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce AExpbExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TPo tpoNode2;
        PExp pexpNode3;
        TPf tpfNode4;
        tpoNode2 = (TPo)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tpfNode4 = (TPf)nodeArrayList3.get(0);

        pexp7Node1 = new AExpbExp7(tpoNode2, pexpNode3, tpfNode4);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce AVarExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        PVar pvarNode2;
        pvarNode2 = (PVar)nodeArrayList1.get(0);

        pexp7Node1 = new AVarExp7(pvarNode2);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce ANombreExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TNombre tnombreNode2;
        tnombreNode2 = (TNombre)nodeArrayList1.get(0);

        pexp7Node1 = new ANombreExp7(tnombreNode2);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce AAppelfoncExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TId tidNode2;
        TPo tpoNode3;
        PListeexp plisteexpNode4;
        TPf tpfNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        plisteexpNode4 = (PListeexp)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);

        pexp7Node1 = new AAppelfoncExp7(tidNode2, tpoNode3, plisteexpNode4, tpfNode5);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce ALireExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TLire tlireNode2;
        TPo tpoNode3;
        TPf tpfNode4;
        tlireNode2 = (TLire)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        tpfNode4 = (TPf)nodeArrayList3.get(0);

        pexp7Node1 = new ALireExp7(tlireNode2, tpoNode3, tpfNode4);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce AVraiExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TVrai tvraiNode2;
        tvraiNode2 = (TVrai)nodeArrayList1.get(0);

        pexp7Node1 = new AVraiExp7(tvraiNode2);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce AFauxExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TFaux tfauxNode2;
        tfauxNode2 = (TFaux)nodeArrayList1.get(0);

        pexp7Node1 = new AFauxExp7(tfauxNode2);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce AIdVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pvarNode1 = new AIdVar(tidNode2);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce AIdbVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TId tidNode2;
        TCo tcoNode3;
        PExp pexpNode4;
        TCf tcfNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tcoNode3 = (TCo)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tcfNode5 = (TCf)nodeArrayList4.get(0);

        pvarNode1 = new AIdbVar(tidNode2, tcoNode3, pexpNode4, tcfNode5);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 9}, {28, SHIFT, 1}, {29, SHIFT, 2}, {30, SHIFT, 3}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 3}, {4, SHIFT, 9}, },
			{{-1, ERROR, 4}, {31, ACCEPT, -1}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, ERROR, 6}, {30, SHIFT, 12}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 9}, {28, SHIFT, 1}, {29, SHIFT, 2}, {30, SHIFT, 3}, },
			{{-1, ERROR, 9}, {5, SHIFT, 15}, {28, SHIFT, 1}, {29, SHIFT, 2}, },
			{{-1, ERROR, 10}, {28, SHIFT, 1}, {29, SHIFT, 2}, },
			{{-1, REDUCE, 9}, {28, SHIFT, 1}, {29, SHIFT, 2}, {30, SHIFT, 3}, },
			{{-1, REDUCE, 4}, {2, SHIFT, 20}, {4, SHIFT, 21}, },
			{{-1, ERROR, 13}, {30, SHIFT, 22}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 15}, {6, SHIFT, 23}, {28, SHIFT, 1}, {29, SHIFT, 2}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, ERROR, 17}, {30, SHIFT, 27}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 20}, {1, SHIFT, 29}, },
			{{-1, ERROR, 21}, {5, SHIFT, 30}, {28, SHIFT, 1}, {29, SHIFT, 2}, },
			{{-1, ERROR, 22}, {4, SHIFT, 21}, },
			{{-1, REDUCE, 20}, {9, SHIFT, 32}, {11, SHIFT, 33}, {14, SHIFT, 34}, {15, SHIFT, 35}, {30, SHIFT, 36}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, REDUCE, 17}, },
			{{-1, ERROR, 26}, {5, SHIFT, 41}, },
			{{-1, REDUCE, 4}, {2, SHIFT, 20}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 29}, {3, SHIFT, 42}, },
			{{-1, ERROR, 30}, {6, SHIFT, 23}, {28, SHIFT, 1}, {29, SHIFT, 2}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, ERROR, 32}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 33}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 34}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 35}, {4, SHIFT, 63}, },
			{{-1, REDUCE, 54}, {2, SHIFT, 64}, {4, SHIFT, 65}, },
			{{-1, ERROR, 37}, {7, SHIFT, 66}, },
			{{-1, REDUCE, 20}, {9, SHIFT, 32}, {11, SHIFT, 33}, {14, SHIFT, 34}, {15, SHIFT, 35}, {30, SHIFT, 36}, },
			{{-1, ERROR, 39}, {21, SHIFT, 68}, },
			{{-1, ERROR, 40}, {6, SHIFT, 23}, },
			{{-1, ERROR, 41}, {6, SHIFT, 23}, {28, SHIFT, 1}, {29, SHIFT, 2}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 45}, {5, SHIFT, 73}, },
			{{-1, REDUCE, 49}, },
			{{-1, ERROR, 47}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 48}, {4, SHIFT, 75}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 51}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, REDUCE, 54}, {2, SHIFT, 64}, {4, SHIFT, 77}, },
			{{-1, ERROR, 53}, {10, SHIFT, 78}, {16, SHIFT, 79}, },
			{{-1, REDUCE, 33}, {17, SHIFT, 80}, },
			{{-1, REDUCE, 35}, {21, SHIFT, 81}, {22, SHIFT, 82}, },
			{{-1, REDUCE, 38}, {23, SHIFT, 83}, {24, SHIFT, 84}, },
			{{-1, REDUCE, 41}, {25, SHIFT, 85}, {26, SHIFT, 86}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 48}, },
			{{-1, ERROR, 61}, {12, SHIFT, 87}, {16, SHIFT, 79}, },
			{{-1, ERROR, 62}, {8, SHIFT, 88}, {16, SHIFT, 79}, },
			{{-1, ERROR, 63}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 64}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, REDUCE, 29}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 68}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 72}, {6, SHIFT, 23}, },
			{{-1, ERROR, 73}, {6, SHIFT, 23}, {28, SHIFT, 1}, {29, SHIFT, 2}, },
			{{-1, ERROR, 74}, {5, SHIFT, 98}, {16, SHIFT, 79}, },
			{{-1, ERROR, 75}, {5, SHIFT, 99}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 29}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 78}, {6, SHIFT, 23}, },
			{{-1, ERROR, 79}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 80}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 81}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 82}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 83}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 84}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 85}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 86}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 87}, {6, SHIFT, 23}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 89}, {5, SHIFT, 111}, {16, SHIFT, 79}, },
			{{-1, ERROR, 90}, {3, SHIFT, 112}, {16, SHIFT, 79}, },
			{{-1, ERROR, 91}, {5, SHIFT, 113}, },
			{{-1, REDUCE, 31}, {0, SHIFT, 114}, {16, SHIFT, 79}, },
			{{-1, ERROR, 93}, {8, SHIFT, 116}, {16, SHIFT, 79}, },
			{{-1, ERROR, 94}, {6, SHIFT, 23}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 3}, {0, SHIFT, 10}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 51}, },
			{{-1, ERROR, 100}, {5, SHIFT, 119}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 32}, {17, SHIFT, 80}, },
			{{-1, REDUCE, 34}, {21, SHIFT, 81}, {22, SHIFT, 82}, },
			{{-1, REDUCE, 36}, {23, SHIFT, 83}, {24, SHIFT, 84}, },
			{{-1, REDUCE, 37}, {23, SHIFT, 83}, {24, SHIFT, 84}, },
			{{-1, REDUCE, 39}, {25, SHIFT, 85}, {26, SHIFT, 86}, },
			{{-1, REDUCE, 40}, {25, SHIFT, 85}, {26, SHIFT, 86}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 23}, {13, SHIFT, 120}, },
			{{-1, ERROR, 111}, {8, SHIFT, 121}, },
			{{-1, REDUCE, 55}, },
			{{-1, ERROR, 113}, {8, SHIFT, 122}, },
			{{-1, ERROR, 114}, {1, SHIFT, 46}, {4, SHIFT, 47}, {18, SHIFT, 48}, {19, SHIFT, 49}, {20, SHIFT, 50}, {27, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 118}, {6, SHIFT, 23}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 120}, {6, SHIFT, 23}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 31}, {0, SHIFT, 114}, {16, SHIFT, 79}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 30}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 4}, },
			{{-1, 11}, {16, 26}, {18, 28}, {24, 40}, {31, 45}, {43, 72}, {70, 94}, {96, 118}, },
			{{-1, 5}, {9, 16}, {10, 18}, {15, 24}, {21, 31}, {30, 43}, {41, 70}, {73, 96}, },
			{{-1, 17}, {0, 6}, {8, 13}, {11, 13}, },
			{{-1, 7}, {8, 14}, {11, 19}, },
			{{-1, 8}, },
			{{-1, 25}, {30, 44}, {40, 69}, {41, 71}, {72, 95}, {73, 97}, {78, 101}, {87, 110}, {94, 117}, {118, 124}, {120, 125}, },
			{{-1, 37}, {38, 67}, },
			{{-1, 38}, },
			{{-1, 91}, {77, 100}, },
			{{-1, 115}, {123, 126}, },
			{{-1, 92}, {32, 53}, {33, 61}, {34, 62}, {47, 74}, {63, 89}, {64, 90}, {68, 93}, {114, 123}, },
			{{-1, 54}, {79, 102}, },
			{{-1, 55}, {80, 103}, },
			{{-1, 56}, {81, 104}, {82, 105}, },
			{{-1, 57}, {83, 106}, {84, 107}, },
			{{-1, 58}, {51, 76}, {85, 108}, {86, 109}, },
			{{-1, 59}, },
			{{-1, 60}, {23, 39}, {38, 39}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'entier', 'bool', id, EOF",
			"expecting: id",
			"expecting: '('",
			"expecting: EOF",
			"expecting: ',', 'entier', 'bool', id, EOF",
			"expecting: ')', 'entier', 'bool'",
			"expecting: 'entier', 'bool'",
			"expecting: ',', '[', '(', 'entier', 'bool', id, EOF",
			"expecting: '{', 'entier', 'bool'",
			"expecting: ',', ')'",
			"expecting: ',', ')', '{', 'entier', 'bool', id, EOF",
			"expecting: nombre",
			"expecting: '}', 'tantque', 'si', 'retour', 'ecrire', id",
			"expecting: ',', '{'",
			"expecting: ')'",
			"expecting: ',', '[', ')', '{', 'entier', 'bool', id, EOF",
			"expecting: ')', '{', 'entier', 'bool', id, EOF",
			"expecting: ']'",
			"expecting: nombre, '(', 'lire', 'vrai', 'faux', '!', id",
			"expecting: '[', '(', '='",
			"expecting: '}'",
			"expecting: '='",
			"expecting: '{'",
			"expecting: ',', ']', ')', ';', 'faire', 'alors', '|', '&', '=', '<', '+', '-', '/', '*'",
			"expecting: ',', '[', ']', '(', ')', ';', 'faire', 'alors', '|', '&', '=', '<', '+', '-', '/', '*'",
			"expecting: 'faire', '|'",
			"expecting: ',', ']', ')', ';', 'faire', 'alors', '|', '&'",
			"expecting: ',', ']', ')', ';', 'faire', 'alors', '|', '&', '=', '<'",
			"expecting: ',', ']', ')', ';', 'faire', 'alors', '|', '&', '=', '<', '+', '-'",
			"expecting: 'alors', '|'",
			"expecting: ';', '|'",
			"expecting: nombre, '(', ')', 'lire', 'vrai', 'faux', '!', id",
			"expecting: '}', 'tantque', 'si', 'sinon', 'retour', 'ecrire', 'entier', 'bool', id, EOF",
			"expecting: ')', '|'",
			"expecting: ']', '|'",
			"expecting: ',', ')', '|'",
			"expecting: '}', 'tantque', 'si', 'sinon', 'retour', 'ecrire', id",
			"expecting: ';'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 3, 4, 1, 3, 0, 5, 6, 0, 7, 1, 3, 8, 9, 1, 10, 3, 11, 5, 2, 12, 13, 0, 14, 15, 16, 17, 8, 9, 18, 18, 18, 2, 19, 20, 12, 21, 22, 8, 10, 13, 0, 14, 23, 18, 2, 23, 23, 18, 24, 25, 26, 27, 28, 23, 23, 23, 23, 29, 30, 18, 18, 31, 32, 20, 18, 0, 13, 0, 22, 8, 33, 14, 23, 31, 22, 18, 18, 18, 18, 18, 18, 18, 18, 22, 12, 33, 34, 14, 35, 30, 22, 0, 13, 0, 23, 23, 14, 12, 26, 27, 28, 28, 23, 23, 23, 23, 36, 37, 23, 37, 18, 14, 12, 0, 22, 23, 22, 12, 12, 35, 0, 12, 14, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
